### ISSUE TITLE
缺少metadata.desktop

### ISSUE THREAD

**Issue by renyuneyun** [fralonra/sddm-chinese-painting-theme#1]
縱觀所有sddm主題，似乎均有metadata.dsktop，而這個主題中並沒有。

metadata.desktop的作用似乎是讓SDDM配置前端（比如plasma的`systemsettings`）識別並展示主題的，所以在某種意義上來說很有必要。

**Comment by fralonra** [comment]
谢谢指点，已添加metadata.desktop
